{
    'name': "custom",
    'summary': "Custom",
    'author': "My Company",
    'website': "https://www.yourcompany.com",
    'category': 'Uncategorized',
    'license':'LGPL-3',
    'version': '19.0.1.0.0',
    'depends': ['base','sale', 'sale_management',
    'product', 'account', 'contacts', 'mrp', 'stock','helpdesk',
    'project','helpdesk_fsm',],
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/server_action.xml",
        "report/timesheet_report.xml",
        "report/timesheet_report_template.xml",
        "views/custom_sale_order_view.xml",
        "views/custom_product_template.xml",
        "views/custom_config_views.xml",
        "views/custom_mrp_bom_views.xml",
        "views/custom_account_move.xml",
        "views/custom_res_partner_views.xml",
        "views/custom_helpdesk_views.xml",
        "views/custom_user_views.xml",
    ],
    "installable": True,
    "application": True,
}